sudo: required

services:
  - docker

before_install:
  - docker build -f ./frontend/Dockerfile.dev -t aryanchugh816/docker-react-testing ./frontend

script:
  - docker run -e CI=true aryanchugh816/docker-react-testing npm run test -- --coverage