version: "3"

services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev

    environment:
      - CHOKIDAR_USEPOLLING=true

    ports:
      - "3000:3000"

    volumes:
      - /app/node_modules
      - ./frontend:/app

  test:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev

    environment: 
      - CHOKIDAR_USEPOLLING=true

    volumes: 
      - /app/node_modules
      - ./frontend:/app

    command: ["npm", "run", "test"]
